# Generated by Django 4.0.1 on 2022-03-02 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abt1_description', models.TextField()),
                ('abt1_cover', models.FileField(upload_to='')),
                ('abt2_heading', models.CharField(max_length=100)),
                ('abt2_description', models.TextField()),
                ('abt3_heading', models.CharField(max_length=100)),
                ('abt3_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Activities_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('phn1', models.IntegerField()),
                ('phn2', models.IntegerField()),
                ('address', models.TextField()),
                ('pin', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=30)),
                ('event_day', models.CharField(max_length=30)),
                ('event_venue', models.CharField(max_length=30)),
                ('event_description', models.TextField()),
                ('event_img1', models.FileField(upload_to='')),
                ('event_img2', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_description', models.TextField()),
                ('book', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Saint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saint_img', models.FileField(upload_to='')),
                ('saint_name', models.CharField(max_length=30)),
                ('saint_title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='')),
                ('word', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_members', models.FileField(upload_to='')),
                ('member_name', models.CharField(max_length=30)),
                ('member_role', models.CharField(max_length=30)),
                ('member_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Unique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='')),
                ('identity_heading', models.TextField()),
                ('identity_data', models.TextField()),
                ('identity_cover', models.FileField(upload_to='')),
                ('mission_data', models.TextField()),
                ('mission_cover', models.FileField(upload_to='')),
                ('location_cover', models.FileField(upload_to='')),
                ('activities_description', models.TextField()),
                ('patron1', models.FileField(upload_to='')),
                ('patron1_name', models.CharField(max_length=30)),
                ('patron1_role', models.CharField(max_length=30)),
                ('patron1_description', models.TextField()),
                ('patron2', models.FileField(upload_to='')),
                ('patron2_name', models.CharField(max_length=30)),
                ('patron2_role', models.CharField(max_length=30)),
                ('patron2_description', models.TextField()),
                ('patron3', models.FileField(upload_to='')),
                ('patron3_name', models.CharField(max_length=30)),
                ('patron3_role', models.CharField(max_length=30)),
                ('patron3_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gallery')),
            ],
        ),
    ]
