# Generated by Django 4.0.1 on 2022-03-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_gallery_category_function_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery_category',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
