# Generated by Django 4.0.1 on 2022-02-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_slider_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=100)),
                ('identity_cover', models.FileField(upload_to='')),
                ('patron1', models.FileField(upload_to='')),
                ('patron1_name', models.CharField(max_length=30)),
                ('patron1_role', models.CharField(max_length=30)),
                ('patron2', models.FileField(upload_to='')),
                ('patron2_name', models.CharField(max_length=30)),
                ('patron2_role', models.CharField(max_length=30)),
                ('patron3', models.FileField(upload_to='')),
                ('patron3_name', models.CharField(max_length=30)),
                ('patron3_role', models.CharField(max_length=30)),
            ],
        ),
    ]
