# Generated by Django 4.0.1 on 2022-04-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gallery_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convent_countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Convents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convent_place', models.CharField(max_length=30)),
                ('convent_country', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
