# Generated by Django 4.0.1 on 2022-02-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unique',
            name='identity',
        ),
        migrations.AddField(
            model_name='unique',
            name='identity_data',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
