# Generated by Django 4.0.1 on 2022-04-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_convent_countries_convents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convents',
            old_name='image',
            new_name='convent_image',
        ),
    ]
