# Generated by Django 4.0.1 on 2022-02-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_unique_identity_unique_identity_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='unique',
            name='identity_heading',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unique',
            name='logo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
