# Generated by Django 4.0.1 on 2022-02-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_unique_identity_heading_unique_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unique',
            name='identity_heading',
            field=models.TextField(),
        ),
    ]
