# Generated by Django 4.0.1 on 2022-02-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_unique_identity_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='unique',
            name='patron1_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unique',
            name='patron2_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unique',
            name='patron3_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
