# Generated by Django 4.0.1 on 2022-02-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_unique_patron1_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unique',
            old_name='patron1',
            new_name='patron',
        ),
        migrations.RenameField(
            model_name='unique',
            old_name='patron1_description',
            new_name='patron_description',
        ),
        migrations.RenameField(
            model_name='unique',
            old_name='patron1_name',
            new_name='patron_name',
        ),
        migrations.RenameField(
            model_name='unique',
            old_name='patron1_role',
            new_name='patron_role',
        ),
        migrations.RemoveField(
            model_name='unique',
            name='patron2',
        ),
        migrations.RemoveField(
            model_name='unique',
            name='patron2_description',
        ),
        migrations.RemoveField(
            model_name='unique',
            name='patron2_name',
        ),
        migrations.RemoveField(
            model_name='unique',
            name='patron2_role',
        ),
        migrations.RemoveField(
            model_name='unique',
            name='patron3',
        ),
        migrations.RemoveField(
            model_name='unique',
            name='patron3_description',
        ),
        migrations.RemoveField(
            model_name='unique',
            name='patron3_name',
        ),
        migrations.RemoveField(
            model_name='unique',
            name='patron3_role',
        ),
    ]
