# Generated by Django 4.0.1 on 2022-02-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_patron_unique_patron1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unique',
            name='location_cover',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
