# Generated by Django 4.0.1 on 2022-02-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_unique_location_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_members', models.FileField(upload_to='')),
            ],
        ),
    ]
