# Generated by Django 4.0.1 on 2022-02-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='member_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='member_role',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
