# Generated by Django 4.0.1 on 2022-02-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_team_member_name_team_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='member_description',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
