# Generated by Django 4.0.1 on 2022-02-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_team_member_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member_description',
            field=models.TextField(),
        ),
    ]
