# Generated by Django 4.0.1 on 2022-02-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_team_member_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saint_img', models.FileField(upload_to='')),
                ('saint_name', models.CharField(max_length=30)),
                ('saint_title', models.CharField(max_length=30)),
            ],
        ),
    ]
