# Generated by Django 4.0.1 on 2022-02-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='unique',
            name='book_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
