# Generated by Django 4.0.1 on 2022-02-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_unique_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balbhavan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balbhavan_image', models.FileField(upload_to='')),
                ('balbhavan_name', models.CharField(max_length=30)),
                ('balbhavan_place', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Couselling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counselling_image', models.FileField(upload_to='')),
                ('counselling_name', models.CharField(max_length=30)),
                ('counselling_place', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_image', models.FileField(upload_to='')),
                ('hospital_name', models.CharField(max_length=30)),
                ('hospital_place', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_image', models.FileField(upload_to='')),
                ('hostel_name', models.CharField(max_length=30)),
                ('hostel_place', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Oldage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldage_image', models.FileField(upload_to='')),
                ('oldage_name', models.CharField(max_length=30)),
                ('oldage_place', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_image', models.FileField(upload_to='')),
                ('school_name', models.CharField(max_length=30)),
                ('school_place', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_image', models.FileField(upload_to='')),
                ('service_name', models.CharField(max_length=30)),
                ('service_place', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='unique',
            name='activities_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
