# Generated by Django 4.0.1 on 2022-02-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_balbhavan_couselling_hospital_hostel_oldage_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unique',
            name='Mission_cover',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unique',
            name='Mission_data',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
