# Generated by Django 4.0.1 on 2022-02-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_unique_mission_cover_unique_mission_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unique',
            old_name='Mission_cover',
            new_name='mission_cover',
        ),
        migrations.RenameField(
            model_name='unique',
            old_name='Mission_data',
            new_name='mission_data',
        ),
    ]
