# Generated by Django 4.0.1 on 2022-02-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abt1_description', models.TextField()),
                ('abt1_cover', models.FileField(upload_to='')),
                ('abt2_description', models.TextField()),
                ('abt3_description', models.TextField()),
            ],
        ),
    ]
