# Generated by Django 4.0.1 on 2022-02-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phn1', models.IntegerField()),
                ('phn2', models.IntegerField()),
                ('address', models.TextField()),
                ('pin', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
