# Generated by Django 4.0.1 on 2022-02-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
