# Generated by Django 4.0.1 on 2022-02-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_about_abt2_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='abt3_heading',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
