# Generated by Django 4.0.1 on 2022-02-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_about_abt3_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='abt2_heading',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='abt3_heading',
            field=models.CharField(max_length=100),
        ),
    ]
