# Generated by Django 4.0.1 on 2022-02-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_about_abt2_heading_alter_about_abt3_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='function_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
