# Generated by Django 4.0.1 on 2022-02-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_gallery_function_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='word',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
