# Generated by Django 4.0.1 on 2022-02-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_slider_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=30)),
                ('event_date', models.CharField(max_length=30)),
                ('event_venue', models.CharField(max_length=30)),
                ('event_description', models.TextField()),
                ('event_img1', models.FileField(upload_to='')),
                ('event_img2', models.FileField(upload_to='')),
            ],
        ),
    ]
