# Generated by Django 4.0.1 on 2022-02-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
    ]
