# Generated by Django 4.0.1 on 2022-02-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_day',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
