# Generated by Django 4.0.1 on 2022-02-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_event_event_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=30)),
            ],
        ),
    ]
