# Generated by Django 4.0.1 on 2022-02-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_gallery_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Balbhavan',
        ),
        migrations.DeleteModel(
            name='Couselling',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='Hostel',
        ),
        migrations.DeleteModel(
            name='Oldage',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
