# Generated by Django 4.0.1 on 2022-02-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_activities_delete_balbhavan_delete_couselling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
    ]
