# Generated by Django 4.0.1 on 2022-02-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_activities_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='book_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
